<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dummybot">

  <!-- Include ros2_control xacro -->
  <xacro:include filename="$(find dummybot_bringup)/description/urdf/dummybot.ros2_control.xacro"/>

  <!-- Properties -->
  <xacro:property name="use_mock_hardware" value="false"/>
  
  <!-- ============================================ -->
  <!-- DIMENSIUNI FIZICE REALE - SISTEM ROS STANDARD -->
  <!-- X = înainte (FAȚĂ) = 36cm (ce tu numești "lățime") -->
  <!-- Y = lateral (STÂNGA-DREAPTA) = 46.5cm (ce tu numești "lungime") -->
  <!-- Z = sus (vertical) -->
  <!-- ============================================ -->
  
  <!-- Roți -->
  <xacro:property name="wheel_radius" value="0.0345"/>     <!-- 69mm diametru / 2 -->
  <xacro:property name="wheel_width" value="0.028"/>       <!-- 28mm grosime -->
  
  <!-- Distanțe între roți -->
  <xacro:property name="wheelbase" value="0.374"/>         <!-- FR-FL distanță FAȚĂ-SPATE (37.4cm) -->
  <xacro:property name="track_width" value="0.390"/>       <!-- FR-RR distanță LATERALĂ (39cm) -->
  
  <!-- Chassis -->
  <xacro:property name="chassis_length" value="0.360"/>    <!-- 36cm pe X (față-spate, "lățimea" ta) -->
  <xacro:property name="chassis_width" value="0.465"/>     <!-- 46.5cm pe Y (lateral, "lungimea" ta) -->
  <xacro:property name="chassis_height" value="0.160"/>    <!-- 16cm înălțime (Z) -->
  
  <xacro:property name="ground_clearance" value="0.050"/>  <!-- 5cm de la sol la baza chassis -->
  
  <!-- Poziționare roți față de chassis -->
  <!-- FR/FL la 5cm de față → +36/2 - 5 = +13cm = +0.13m -->
  <!-- RR/RL la 3cm de spate → -36/2 + 3 = -15cm = -0.15m -->
  <!-- Verificare: 13cm + 15cm = 28cm (ar trebui ~37.4cm pentru wheelbase) -->
  <!-- Corectie: 5cm față, 32.4cm spate? Sau 18.7cm față, 18.7cm spate? -->
  
  <!-- Să recalculăm cu wheelbase = 37.4cm: -->
  <!-- Centru roți față: +37.4/2 = +18.7cm -->
  <!-- Centru roți spate: -37.4/2 = -18.7cm -->
  <xacro:property name="front_wheel_x" value="0.187"/>     <!-- +18.7cm -->
  <xacro:property name="rear_wheel_x" value="-0.187"/>     <!-- -18.7cm -->
  
  <!-- Offset vertical roți: centru la 5.8cm de sol, minus ground_clearance de 5cm -->
  <xacro:property name="wheel_z_offset" value="0.008"/>    <!-- 5.8cm - 5cm = 0.8cm -->
  
  <!-- LiDAR poziționare -->
  <!-- "12cm de la fața carcasei până la început LiDAR" -->
  <!-- Dacă fața chassis e la +18cm, iar LiDAR începe la +12cm de la față... -->
  <!-- Stai, trebuie clarificat: 12cm de la MARGINEA chassis sau de la CENTRU? -->
  <!-- Presupun: 12cm de la MARGINEA din față (la +18cm) -->
  <!-- Deci început LiDAR = +18cm - 12cm = +6cm de la centru -->
  <!-- Centru LiDAR = +6cm + 1.9cm (jumătate) = +7.9cm = 0.079m -->
  <xacro:property name="lidar_x_offset" value="0.079"/>    <!-- 7.9cm înainte de centru -->
  <xacro:property name="lidar_z_offset" value="0.1775"/>   <!-- 17.75cm deasupra base_chassis -->
  
  <!-- ESP32 Hardware Interface -->
  <xacro:property name="serial_port" value="/dev/ttyESP32"/>
  <xacro:property name="serial_baud" value="115200"/>
  <xacro:property name="ticks_per_revolution" value="1760"/>

  <!-- Materials -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  
  <material name="dark_grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <!-- ============================================ -->
  <!-- BASE LINK (ROOT FRAME) -->
  <!-- ============================================ -->
  <link name="base_link"/>
  
  <joint name="base_link_chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_chassis"/>
    <origin xyz="0 0 ${ground_clearance}" rpy="0 0 ${-pi/2}"/>
  </joint>

  <!-- ============================================ -->
  <!-- BASE CHASSIS -->
  <!-- ============================================ -->
  <link name="base_chassis">
    <visual>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.0833" ixy="0.0" ixz="0.0" 
               iyy="0.1042" iyz="0.0" 
               izz="0.1667"/>
    </inertial>
  </link>

  <!-- ============================================ -->
  <!-- WHEEL MACRO -->
  <!-- ============================================ -->
  <xacro:macro name="wheel" params="prefix x y">
  
    <link name="${prefix}_wheel_link">
      <visual>
        <!-- FĂRĂ rotație aici -->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <!-- FĂRĂ rotație aici -->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                iyy="0.0001" iyz="0.0"
                izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_chassis"/>
      <child link="${prefix}_wheel_link"/>
      <!-- ROTAȚIE AICI în joint origin -->
      <origin xyz="${x} ${y} ${wheel_z_offset}" rpy="0 ${pi/2} 0"/>
      <!-- Axa Y = roata se rotește în jurul axei laterale -->
      <axis xyz="0 0 1"/>
    </joint>
    
  </xacro:macro>

  <!-- ============================================ -->
  <!-- INSTANTIATE 4 WHEELS -->
  <!-- FR = Front Right (față + dreapta, Y negativ) -->
  <!-- FL = Front Left (față + stânga, Y pozitiv) -->
  <!-- RR = Rear Right (spate + dreapta, Y negativ) -->
  <!-- RL = Rear Left (spate + stânga, Y pozitiv) -->
  <!-- ============================================ -->
  
  <!-- CORECT: Swap X cu Y -->
  <!-- Front Left (față + stânga) -->
  <xacro:wheel prefix="front_left"  x="${track_width/2}"  y="${-front_wheel_x}"/>

  <!-- Front Right (față + dreapta) -->
  <xacro:wheel prefix="front_right" x="${track_width/2}"  y="${front_wheel_x}"/>

  <!-- Rear Left (spate + stânga) -->
  <xacro:wheel prefix="rear_left"   x="${-track_width/2}"  y="${-rear_wheel_x}"/>

  <!-- Rear Right (spate + dreapta) -->
  <xacro:wheel prefix="rear_right"  x="${-track_width/2}"  y="${rear_wheel_x}"/>

  <!-- ============================================ -->
  <!-- LiDAR -->
  <!-- ============================================ -->
  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.035 0.035 0.035"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.035 0.035 0.035"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.15"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_chassis"/>
    <child link="laser_frame"/>
    <origin xyz="0 0.079 0.1775" rpy="0 0 ${-pi/2}"/>
  </joint>

  <!-- ============================================ -->
  <!-- ROS2 CONTROL -->
  <!-- ============================================ -->
  <xacro:dummybot_ros2_control 
    name="DummyBotSystem"
    serial_port="${serial_port}"
    serial_baud="${serial_baud}"
    wheel_radius="${wheel_radius}"
    wheel_separation="${track_width}"
    ticks_per_revolution="${ticks_per_revolution}"/>

</robot>