<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dummybot">

  <!-- Include ros2_control xacro -->
  <xacro:include filename="$(find dummybot_bringup)/description/urdf/dummybot.ros2_control.xacro"/>

  <!-- Properties -->
  <xacro:property name="use_mock_hardware" value="false"/>
  
  <!-- Robot dimensions -->
  <xacro:property name="wheel_radius" value="0.0345"/>
  <xacro:property name="wheel_width" value="0.028"/>
  <xacro:property name="wheelbase" value="0.374"/>            <!-- Track width (lateral X) -->
  <xacro:property name="wheel_separation" value="0.390"/>     <!-- Wheelbase (longitudinal Y) -->
  
  <xacro:property name="base_length" value="0.36"/>           <!-- X (scurt) -->
  <xacro:property name="base_width" value="0.46"/>            <!-- Y (lung) -->
  <xacro:property name="base_height" value="0.14"/>
  
  <!-- Ground clearance: centru roată la 1.45cm + 2cm la bază = 3.45cm -->
  <xacro:property name="ground_clearance" value="0.0345"/>
  <xacro:property name="wheel_z_offset" value="-0.02"/>
  
  <!-- Poziții roți pe Y (față-spate) -->
  <xacro:property name="front_wheel_y_offset" value="0.175"/>   <!-- Față (pozitiv) ✅ INVERSAT -->
  <xacro:property name="rear_wheel_y_offset" value="-0.215"/>   <!-- Spate (negativ) ✅ INVERSAT -->
  
  <!-- Serial configuration -->
  <xacro:property name="serial_port" value="/dev/ttyESP32"/>
  <xacro:property name="serial_baud" value="115200"/>
  <xacro:property name="ticks_per_revolution" value="1760"/>

  <!-- Materials -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  
  <material name="dark_grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <!-- Base Footprint (pe sol) -->
  <link name="base_footprint"/>
  
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <!-- Baza chassis la 3.45cm deasupra solului ✅ -->
    <origin xyz="0 0 ${ground_clearance}" rpy="0 0 0"/>
  </joint>

  <!-- Base Link (FĂRĂ offset pe visual acum, origin e la bază) -->
  <link name="base_link">
    <visual>
      <!-- Origin la bază (jos), geometry crește în sus ✅ -->
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.0833" ixy="0.0" ixz="0.0" 
               iyy="0.1042" iyz="0.0" 
               izz="0.1667"/>
    </inertial>
  </link>

  <!-- Wheel Macro cu ROTAȚIE 90° pe Z ✅ -->
  <xacro:macro name="wheel" params="prefix x y">
    
    <link name="${prefix}_wheel_link">
      <visual>
        <!-- Rotație: 90° pe Z pentru axa X să fie axa de rotație ✅ -->
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x} ${y} ${wheel_z_offset}" rpy="0 0 0"/>
      <!-- Axa de rotație: Y pentru roți pe X-axis ✅ -->
      <axis xyz="1 0 0"/>
    </joint>
    
  </xacro:macro>

  <!-- Instantiate 4 wheels - FAȚĂ = +Y (pozitiv) ✅ -->
  <xacro:wheel prefix="front_left"  x="${wheelbase/2}"   y="${front_wheel_y_offset}"/>
  <xacro:wheel prefix="front_right" x="${-wheelbase/2}"  y="${front_wheel_y_offset}"/>
  <xacro:wheel prefix="rear_left"   x="${wheelbase/2}"   y="${rear_wheel_y_offset}"/>
  <xacro:wheel prefix="rear_right"  x="${-wheelbase/2}"  y="${rear_wheel_y_offset}"/>

  <!-- LiDAR - FAȚĂ = +Y (pozitiv) ✅ -->
  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.035 0.035 0.035"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.035 0.035 0.035"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.15"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <!-- LiDAR în FAȚĂ: Y pozitiv = +0.10m ✅ INVERSAT -->
    <origin xyz="0 0.10 ${base_height + 0.0175}" rpy="0 0 0"/>
  </joint>

  <!-- Include ros2_control -->
  <xacro:dummybot_ros2_control 
    name="DummyBotSystem"
    serial_port="${serial_port}"
    serial_baud="${serial_baud}"
    wheel_radius="${wheel_radius}"
    wheel_separation="${wheel_separation}"
    ticks_per_revolution="${ticks_per_revolution}"/>

</robot>